### PR TITLE
wip: feat: bridge2 accessible in /gw/

### PR DESCRIPTION
**Pull request by ajbouh**
Live editing of ui is enabled not enabled by default.

Dockerfile works to build and start running bridge2

TODO use PORT environment variable in main.go
TODO use environment variable to know base URL

### CODE REVIEW

**Comment by ajbouh** [comment]
cc @mgood

**Comment by mgood** [comment]
I guess there's probably 2 remaining things to do on this:
[] environment variable to set prefix path
[] respect the `PORT` variable

**Comment by mgood** [comment]
@ajbouh I can keep working on those and make PRs on top of this, or do you want to just merge and I can fix those after?

**Comment by ajbouh** [comment]
let's merge the bridge2 prep branch

**Comment by ajbouh** [comment]
then you can decide whether or not your workflow in this branch is good enough to merge

**Comment by mgood** [comment]
Ok, I've rebased the commits on this branch. I think it's in a reasonable state to push to continue work. Though the other companion services like the `transcriber` are not yet running in substrate IIUC, so this still needs to be run with its own `docker-compose` setup until those are ready.
@ajbouh anything else you think needs to be done first?

**Comment by ajbouh** [comment]
The complete functionality of transcriber and translator are now in faster-whisper and seamlessm4t

**Comment by mgood** [comment]
@ajbouh I added an env var to specify the transcription URL, though it seems like there's an error when substrate tries to spawn faster-whisper:
```
Feb 14 21:18:02 substrate.home.arpa substrate[89075]: ServiceSpawnResolution() viewspec= r=activityspec.ServiceSpawnResolution{User:"", Ephemeral:false, ServiceName:"faster-whisper", Parameters:activityspec.ServiceSpawnParameters{}, GracePeriodSeconds:(*int)(nil), ServiceDefSpawn:activityspec.ServiceDefSpawn{Image:"ghcr.io/ajbouh/substrate:substrate-faster-whisper", Environment:map[string]string{"CUDA_DEVICE_ORDER":"PCI_BUS_ID", "CUDA_VISIBLE_DEVICES":"0", "INTERNAL_SUBSTRATE_HOST":"substrate:8080", "INTERNAL_SUBSTRATE_PROTOCOL":"http:", "JAMSOCKET_IFRAME_DOMAIN":"https://substrate.home.arpa", "JAMSOCKET_SUBSTRATE_ORIGIN":"https://substrate.home.arpa", "MODEL_COMPUTE_TYPE":"float16", "MODEL_DEVICE":"cuda", "MODEL_REPO":"/res/large-v3/huggingface/local", "ORIGIN":"https://substrate.home.arpa", "PORT":"8080", "PUBLIC_EXTERNAL_ORIGIN":"https://substrate.home.arpa", "SUBSTRATE_URL_PREFIX":"/faster-whisper/"}, Command:[]string{"--port", "8080"}, ResourceDirs:map[string]activityspec.ResourceDirDef{"large-v3":activityspec.ResourceDirDef{ID:"huggingface:model:Systran/faster-whisper-large-v3:edaa852ec7e145841d8ffdb056a99866b5f0a478", SHA256:"b81ef49420b1664f048ffc1bc43dc315da6f87c1ccd521bf8be24d26dfa69b49"}, "tiny":activityspec.ResourceDirDef{ID:"huggingface:model:Systran/faster-whisper-tiny:d90ca5fe260221311c53c58e660288d3deb8d356", SHA256:"48cc6140b44fbd20db1bfd4edb7650a627c7172559398af6fbc655444b068db8"}}, Mounts:[]activityspec.ServiceDefSpawnMount(nil), URLPrefix:""}}
Feb 14 21:18:02 substrate.home.arpa substrate[89075]: provisioner.go:53: err in handler: statfs /var/lib/resourcedirs/b81ef49420b1664f048ffc1bc43dc315da6f87c1ccd521bf8be24d26dfa69b49: no such file or directory
```

**Pull request merged**
